/* Generates the idempotent seed migration from the normalized catalog (source of truth). */
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { catalogProducts, catalogMemberships } from '../src/lib/catalog/catalog';

const __dirname = dirname(fileURLToPath(import.meta.url));
const out = join(__dirname, '..', 'supabase', 'migrations', '20260806090100_seed_catalog.sql');

const q = (s: string | undefined | null) => (s == null ? 'null' : `'${String(s).replace(/'/g, "''")}'`);
const b = (v: boolean) => (v ? 'true' : 'false');
const n = (v: number | undefined | null) => (v == null ? 'null' : String(v));

let sql = `-- AUTO-GENERATED by scripts/gen-seed-sql.ts from the normalized catalog.
-- Idempotent: re-running upserts by slug / (product_id, variant_key). Money in cents.
-- Seeds ALL products (incl. hidden future) and ALL memberships so the admin can
-- manage future releases. Storefront RLS still only exposes visible/active rows.

`;

for (const p of catalogProducts) {
  sql += `insert into public.catalog_products
  (slug, app_product_id, display_name, short_name, subtitle, category, dosage_form_summary,
   short_description, long_description, image_url, image_alt, starting_price_cents, currency,
   status, is_visible, launch_phase, campaign_theme, requires_provider_review, requires_prescription,
   requires_compliance_review, requires_pharmacy_verification)
values (${q(p.slug)}, ${q(p.appId)}, ${q(p.displayName)}, ${q(p.shortName)}, ${q(p.subtitle)}, ${q(p.category)}, ${q(p.dosageFormSummary)},
   ${q(p.shortDescription)}, ${q(p.longDescription)}, ${q(p.imageUrl)}, ${q(p.imageAlt)}, ${n(p.startingPriceCents)}, ${q(p.currency)},
   ${q(p.status)}, ${b(p.isVisible)}, ${n(p.launchPhase)}, ${q(p.campaignTheme)}, ${b(p.requiresProviderReview)}, ${b(p.requiresPrescription)},
   ${b(p.requiresComplianceReview)}, ${b(p.requiresPharmacyVerification)})
on conflict (slug) do update set
  app_product_id = excluded.app_product_id, display_name = excluded.display_name, short_name = excluded.short_name,
  subtitle = excluded.subtitle, category = excluded.category, dosage_form_summary = excluded.dosage_form_summary,
  short_description = excluded.short_description, long_description = excluded.long_description, image_url = excluded.image_url,
  image_alt = excluded.image_alt, starting_price_cents = excluded.starting_price_cents, currency = excluded.currency,
  status = excluded.status, is_visible = excluded.is_visible, launch_phase = excluded.launch_phase,
  campaign_theme = excluded.campaign_theme, requires_provider_review = excluded.requires_provider_review,
  requires_prescription = excluded.requires_prescription, requires_compliance_review = excluded.requires_compliance_review,
  requires_pharmacy_verification = excluded.requires_pharmacy_verification;\n\n`;

  for (const v of p.variants) {
    sql += `insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, ${q(v.variantKey)}, ${q(v.displayName)}, ${q(v.dosageForm)}, ${q(v.strength)}, ${q(v.size)}, ${n(v.priceCents)}, ${q(v.currency)}, ${q(v.billingType)}, ${v.billingInterval ? q(v.billingInterval) : 'null'}, ${b(v.isActive)}, ${n(v.sortOrder)}
from public.catalog_products p where p.slug = ${q(p.slug)}
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;\n`;
  }
  sql += '\n';
}

for (const m of catalogMemberships) {
  const formulations = JSON.stringify(m.includedFormulations).replace(/'/g, "''");
  sql += `insert into public.catalog_memberships
  (slug, app_product_id, display_name, brand_name, short_description, long_description, monthly_price_cents, currency,
   billing_interval, initial_term_months, locked_rate, included_formulations, maximum_included_formulation,
   provider_review_required, prescription_guaranteed, shipping_included, status, is_visible)
values (${q(m.slug)}, ${q(m.checkoutProductId)}, ${q(m.displayName)}, ${q(m.brandName)}, ${q(m.shortDescription)}, ${q(m.longDescription)}, ${n(m.monthlyPriceCents)}, ${q(m.currency)},
   ${q(m.billingInterval)}, ${n(m.initialTermMonths)}, ${b(m.lockedRate)}, '${formulations}'::jsonb, ${q(m.maximumIncludedFormulation)},
   ${b(m.providerReviewRequired)}, ${b(m.prescriptionGuaranteed)}, ${b(m.shippingIncluded)}, ${q(m.status)}, ${b(m.isVisible)})
on conflict (slug) do update set
  app_product_id = excluded.app_product_id, display_name = excluded.display_name, brand_name = excluded.brand_name,
  short_description = excluded.short_description, long_description = excluded.long_description,
  monthly_price_cents = excluded.monthly_price_cents, currency = excluded.currency, billing_interval = excluded.billing_interval,
  initial_term_months = excluded.initial_term_months, locked_rate = excluded.locked_rate,
  included_formulations = excluded.included_formulations, maximum_included_formulation = excluded.maximum_included_formulation,
  provider_review_required = excluded.provider_review_required, prescription_guaranteed = excluded.prescription_guaranteed,
  shipping_included = excluded.shipping_included, status = excluded.status, is_visible = excluded.is_visible;\n\n`;
}

writeFileSync(out, sql);
console.log(`Wrote ${out} (${sql.length} bytes)`);
