-- MBM-TAGADA-MANUAL-VARIANT-CREATION-1
-- Additive kashu_sku_map upsert for 10 vial-specific one-time SKUs.
--
-- DO NOT APPLY until the owner pastes live Tagada variant_id / price_id values
-- from dashboard create on the EXISTING product families:
--   product_6b750325addf  (SEM B12)
--   product_dcc64482bbbf  (SEM Glycine)
--   product_74cd4752c9d6  (TIR B12)
--   product_861e0edd8ab2  (TIR Glycine)
--
-- Rules:
--   - these 10 SKUs only
--   - INSERT ... ON CONFLICT (mbm_sku) DO UPDATE
--   - no deletes, no truncates, no unrelated rows
--   - no historical price deletion
--   - no GEN changes
--   - do not invent Tagada IDs
--
-- Apply via Bolt/Supabase only after explicit owner approval.
-- Do not apply from Cursor while placeholders remain.

do $$
begin
  raise notice 'MBM-TAGADA-MANUAL-VARIANT-CREATION-1: kashu_sku_map upsert is not applied. Paste live Tagada variant_id / price_id, then uncomment the INSERT below.';
end $$;

-- After owner provides IDs:
-- 1. Replace every PASTE_TAGADA_VARIANT_ID / PASTE_TAGADA_PRICE_ID below.
-- 2. Uncomment the INSERT ... ON CONFLICT block.
-- 3. Confirm tagada_price_cents equals mbm_price_cents on each row.
-- 4. Apply via Bolt/Supabase.
--
-- insert into public.kashu_sku_map (
--   mbm_sku, mbm_product_id, mbm_variant_id,
--   tagada_product_id, tagada_variant_id, tagada_price_id,
--   mbm_price_cents, tagada_price_cents, is_active, notes, updated_at
-- ) values
--   -- SEM B12 · 2 mg vial · $99 · website weekly dose 0.5 mg
--   (
--     'MBM-WM-SEM-B12-005', 'p1', 'sem-b12-2mg',
--     'product_6b750325addf',
--     'PASTE_TAGADA_VARIANT_ID',  -- owner paste variant_...
--     'PASTE_TAGADA_PRICE_ID',    -- owner paste price_...
--     9900, 9900, true,
--     'MBM-TAGADA-MANUAL-VARIANT-CREATION-1 SEM B12 2mg vial',
--     now()
--   ),
--   -- SEM B12 · 10 mg vial · $119 · website weekly doses 1.75 mg, 2 mg
--   (
--     'MBM-WM-SEM-B12-006', 'p1', 'sem-b12-10mg',
--     'product_6b750325addf',
--     'PASTE_TAGADA_VARIANT_ID',
--     'PASTE_TAGADA_PRICE_ID',
--     11900, 11900, true,
--     'MBM-TAGADA-MANUAL-VARIANT-CREATION-1 SEM B12 10mg vial',
--     now()
--   ),
--   -- SEM Glycine · 2 mg vial · $99 · website weekly dose 0.5 mg
--   (
--     'MBM-WM-SEM-GLY-005', 'p1', 'sem-glycine-2mg',
--     'product_dcc64482bbbf',
--     'PASTE_TAGADA_VARIANT_ID',
--     'PASTE_TAGADA_PRICE_ID',
--     9900, 9900, true,
--     'MBM-TAGADA-MANUAL-VARIANT-CREATION-1 SEM GLY 2mg vial',
--     now()
--   ),
--   -- SEM Glycine · 10 mg vial · $119 · website weekly doses 1.75 mg, 2 mg
--   (
--     'MBM-WM-SEM-GLY-006', 'p1', 'sem-glycine-10mg',
--     'product_dcc64482bbbf',
--     'PASTE_TAGADA_VARIANT_ID',
--     'PASTE_TAGADA_PRICE_ID',
--     11900, 11900, true,
--     'MBM-TAGADA-MANUAL-VARIANT-CREATION-1 SEM GLY 10mg vial',
--     now()
--   ),
--   -- TIR B12 · 20 mg vial · $139 · website weekly dose 5 mg
--   (
--     'MBM-WM-TIR-B12-005', 'p5', 'tir-b12-10mg-ml',
--     'product_74cd4752c9d6',
--     'PASTE_TAGADA_VARIANT_ID',
--     'PASTE_TAGADA_PRICE_ID',
--     13900, 13900, true,
--     'MBM-TAGADA-MANUAL-VARIANT-CREATION-1 TIR B12 20mg vial',
--     now()
--   ),
--   -- TIR B12 · 40 mg vial · $159 · website weekly dose 10 mg
--   (
--     'MBM-WM-TIR-B12-006', 'p5', 'tir-b12-20mg-ml',
--     'product_74cd4752c9d6',
--     'PASTE_TAGADA_VARIANT_ID',
--     'PASTE_TAGADA_PRICE_ID',
--     15900, 15900, true,
--     'MBM-TAGADA-MANUAL-VARIANT-CREATION-1 TIR B12 40mg vial',
--     now()
--   ),
--   -- TIR B12 · 60 mg vial · $179 · website weekly dose 15 mg
--   (
--     'MBM-WM-TIR-B12-007', 'p5', 'tir-b12-30mg-ml',
--     'product_74cd4752c9d6',
--     'PASTE_TAGADA_VARIANT_ID',
--     'PASTE_TAGADA_PRICE_ID',
--     17900, 17900, true,
--     'MBM-TAGADA-MANUAL-VARIANT-CREATION-1 TIR B12 60mg vial',
--     now()
--   ),
--   -- TIR Glycine · 20 mg vial · $139 · website weekly dose 5 mg
--   (
--     'MBM-WM-TIR-GLY-005', 'p5', 'tir-glycine-10mg-ml',
--     'product_861e0edd8ab2',
--     'PASTE_TAGADA_VARIANT_ID',
--     'PASTE_TAGADA_PRICE_ID',
--     13900, 13900, true,
--     'MBM-TAGADA-MANUAL-VARIANT-CREATION-1 TIR GLY 20mg vial',
--     now()
--   ),
--   -- TIR Glycine · 40 mg vial · $159 · website weekly dose 10 mg
--   (
--     'MBM-WM-TIR-GLY-006', 'p5', 'tir-glycine-20mg-ml',
--     'product_861e0edd8ab2',
--     'PASTE_TAGADA_VARIANT_ID',
--     'PASTE_TAGADA_PRICE_ID',
--     15900, 15900, true,
--     'MBM-TAGADA-MANUAL-VARIANT-CREATION-1 TIR GLY 40mg vial',
--     now()
--   ),
--   -- TIR Glycine · 60 mg vial · $179 · website weekly dose 15 mg
--   (
--     'MBM-WM-TIR-GLY-007', 'p5', 'tir-glycine-30mg-ml',
--     'product_861e0edd8ab2',
--     'PASTE_TAGADA_VARIANT_ID',
--     'PASTE_TAGADA_PRICE_ID',
--     17900, 17900, true,
--     'MBM-TAGADA-MANUAL-VARIANT-CREATION-1 TIR GLY 60mg vial',
--     now()
--   )
-- on conflict (mbm_sku) do update set
--   mbm_product_id = excluded.mbm_product_id,
--   mbm_variant_id = excluded.mbm_variant_id,
--   tagada_product_id = excluded.tagada_product_id,
--   tagada_variant_id = excluded.tagada_variant_id,
--   tagada_price_id = excluded.tagada_price_id,
--   mbm_price_cents = excluded.mbm_price_cents,
--   tagada_price_cents = excluded.tagada_price_cents,
--   is_active = true,
--   notes = excluded.notes,
--   updated_at = now();
