-- AUTO-GENERATED by scripts/gen-seed-sql.ts from the normalized catalog.
-- Idempotent: re-running upserts by slug / (product_id, variant_key). Money in cents.
-- Seeds ALL products (incl. hidden future) and ALL memberships so the admin can
-- manage future releases. Storefront RLS still only exposes visible/active rows.

insert into public.catalog_products
  (slug, app_product_id, display_name, short_name, subtitle, category, dosage_form_summary,
   short_description, long_description, image_url, image_alt, starting_price_cents, currency,
   status, is_visible, launch_phase, campaign_theme, requires_provider_review, requires_prescription,
   requires_compliance_review, requires_pharmacy_verification)
values ('semaglutide', 'p1', 'Semaglutide + B6 Injection', 'Semaglutide', 'Provider-directed weight management', 'weight-management', 'Injection',
   'A provider-directed weight-management injection pairing semaglutide with vitamin B6.', 'Prescription weight-management option available following licensed-provider evaluation. Exact formulation, concentration, and treatment plan are determined by the prescribing provider and dispensing pharmacy.', '/images/products/file_0000000081dc822f831112a2c1e5d3d9 copy.png', 'Amber injection vial for Semaglutide + B6, a provider-directed weight-management option', 14900, 'usd',
   'active', true, null, null, true, true,
   true, true)
on conflict (slug) do update set
  app_product_id = excluded.app_product_id, display_name = excluded.display_name, short_name = excluded.short_name,
  subtitle = excluded.subtitle, category = excluded.category, dosage_form_summary = excluded.dosage_form_summary,
  short_description = excluded.short_description, long_description = excluded.long_description, image_url = excluded.image_url,
  image_alt = excluded.image_alt, starting_price_cents = excluded.starting_price_cents, currency = excluded.currency,
  status = excluded.status, is_visible = excluded.is_visible, launch_phase = excluded.launch_phase,
  campaign_theme = excluded.campaign_theme, requires_provider_review = excluded.requires_provider_review,
  requires_prescription = excluded.requires_prescription, requires_compliance_review = excluded.requires_compliance_review,
  requires_pharmacy_verification = excluded.requires_pharmacy_verification;

insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'semaglutide-v1', '1mg/1mg per mL, 2mL', 'Injection', '1mg/1mg per mL', '2mL', 14900, 'usd', 'one_time', null, true, 0
from public.catalog_products p where p.slug = 'semaglutide'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;
insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'semaglutide-v2', '2mg/2mg per mL, 2mL', 'Injection', '2mg/2mg per mL', '2mL', 16900, 'usd', 'one_time', null, true, 1
from public.catalog_products p where p.slug = 'semaglutide'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;
insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'semaglutide-v3', '5mg/2mg per mL, 2mL', 'Injection', '5mg/2mg per mL', '2mL', 19900, 'usd', 'one_time', null, true, 2
from public.catalog_products p where p.slug = 'semaglutide'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;

insert into public.catalog_products
  (slug, app_product_id, display_name, short_name, subtitle, category, dosage_form_summary,
   short_description, long_description, image_url, image_alt, starting_price_cents, currency,
   status, is_visible, launch_phase, campaign_theme, requires_provider_review, requires_prescription,
   requires_compliance_review, requires_pharmacy_verification)
values ('tirzepatide', 'p5', 'Tirzepatide + B6 Injection', 'Tirzepatide', 'Provider-directed weight management', 'weight-management', 'Injection',
   'A provider-directed weight-management injection pairing tirzepatide with vitamin B6.', 'Prescription weight-management option available following licensed-provider evaluation. Exact formulation, concentration, and treatment plan are determined by the prescribing provider and dispensing pharmacy.', '/images/products/file_0000000081dc822f831112a2c1e5d3d9 copy.png', 'Amber injection vial for Tirzepatide + B6, a provider-directed weight-management option', 19900, 'usd',
   'active', true, null, null, true, true,
   true, true)
on conflict (slug) do update set
  app_product_id = excluded.app_product_id, display_name = excluded.display_name, short_name = excluded.short_name,
  subtitle = excluded.subtitle, category = excluded.category, dosage_form_summary = excluded.dosage_form_summary,
  short_description = excluded.short_description, long_description = excluded.long_description, image_url = excluded.image_url,
  image_alt = excluded.image_alt, starting_price_cents = excluded.starting_price_cents, currency = excluded.currency,
  status = excluded.status, is_visible = excluded.is_visible, launch_phase = excluded.launch_phase,
  campaign_theme = excluded.campaign_theme, requires_provider_review = excluded.requires_provider_review,
  requires_prescription = excluded.requires_prescription, requires_compliance_review = excluded.requires_compliance_review,
  requires_pharmacy_verification = excluded.requires_pharmacy_verification;

insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'tirzepatide-v1', '5mg/2mg per mL, 2mL', 'Injection', '5mg/2mg per mL', '2mL', 19900, 'usd', 'one_time', null, true, 0
from public.catalog_products p where p.slug = 'tirzepatide'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;
insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'tirzepatide-v2', '15mg/2mg per mL, 2mL', 'Injection', '15mg/2mg per mL', '2mL', 26900, 'usd', 'one_time', null, true, 1
from public.catalog_products p where p.slug = 'tirzepatide'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;
insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'tirzepatide-v3', '25mg/2mg per mL, 2mL', 'Injection', '25mg/2mg per mL', '2mL', 37900, 'usd', 'one_time', null, true, 2
from public.catalog_products p where p.slug = 'tirzepatide'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;
insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'tirzepatide-v4', '30mg/2mg per mL, 2mL', 'Injection', '30mg/2mg per mL', '2mL', 44900, 'usd', 'one_time', null, true, 3
from public.catalog_products p where p.slug = 'tirzepatide'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;

insert into public.catalog_products
  (slug, app_product_id, display_name, short_name, subtitle, category, dosage_form_summary,
   short_description, long_description, image_url, image_alt, starting_price_cents, currency,
   status, is_visible, launch_phase, campaign_theme, requires_provider_review, requires_prescription,
   requires_compliance_review, requires_pharmacy_verification)
values ('estradiol-patch', 'p16', 'Estradiol Patch', 'Estradiol Patch', 'Provider-directed hormone therapy', 'womens-hormone-therapy', 'Patch',
   'A transdermal estradiol patch prescribed as part of provider-directed hormone therapy.', 'Prescription option available following licensed-provider evaluation. Exact formulation, concentration, and treatment plan are determined by the prescribing provider and dispensing pharmacy.', '/images/products/patches.png', 'Estradiol transdermal patch, a provider-directed hormone therapy option', 11900, 'usd',
   'active', true, null, null, true, true,
   true, true)
on conflict (slug) do update set
  app_product_id = excluded.app_product_id, display_name = excluded.display_name, short_name = excluded.short_name,
  subtitle = excluded.subtitle, category = excluded.category, dosage_form_summary = excluded.dosage_form_summary,
  short_description = excluded.short_description, long_description = excluded.long_description, image_url = excluded.image_url,
  image_alt = excluded.image_alt, starting_price_cents = excluded.starting_price_cents, currency = excluded.currency,
  status = excluded.status, is_visible = excluded.is_visible, launch_phase = excluded.launch_phase,
  campaign_theme = excluded.campaign_theme, requires_provider_review = excluded.requires_provider_review,
  requires_prescription = excluded.requires_prescription, requires_compliance_review = excluded.requires_compliance_review,
  requires_pharmacy_verification = excluded.requires_pharmacy_verification;

insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'estradiol-patch-v1', '0.025mg twice weekly, 8 patches', 'Patch', '0.025mg twice weekly', '8 patches', 11900, 'usd', 'one_time', null, true, 0
from public.catalog_products p where p.slug = 'estradiol-patch'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;
insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'estradiol-patch-v2', '0.05mg twice weekly, 8 patches', 'Patch', '0.05mg twice weekly', '8 patches', 11900, 'usd', 'one_time', null, true, 1
from public.catalog_products p where p.slug = 'estradiol-patch'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;
insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'estradiol-patch-v3', '0.1mg twice weekly, 8 patches', 'Patch', '0.1mg twice weekly', '8 patches', 13500, 'usd', 'one_time', null, true, 2
from public.catalog_products p where p.slug = 'estradiol-patch'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;

insert into public.catalog_products
  (slug, app_product_id, display_name, short_name, subtitle, category, dosage_form_summary,
   short_description, long_description, image_url, image_alt, starting_price_cents, currency,
   status, is_visible, launch_phase, campaign_theme, requires_provider_review, requires_prescription,
   requires_compliance_review, requires_pharmacy_verification)
values ('progesterone-capsules', 'p23', 'Progesterone Capsules', 'Progesterone', 'Provider-directed hormone therapy', 'womens-hormone-therapy', 'Capsule',
   'Oral progesterone capsules prescribed as part of provider-directed hormone therapy.', 'Prescription option available following licensed-provider evaluation. Exact formulation, concentration, and treatment plan are determined by the prescribing provider and dispensing pharmacy.', '/images/products/file_00000000e110822fb1dd36d19b3c9896 copy.png', 'Progesterone capsules bottle, a provider-directed hormone therapy option', 4900, 'usd',
   'active', true, null, null, true, true,
   true, true)
on conflict (slug) do update set
  app_product_id = excluded.app_product_id, display_name = excluded.display_name, short_name = excluded.short_name,
  subtitle = excluded.subtitle, category = excluded.category, dosage_form_summary = excluded.dosage_form_summary,
  short_description = excluded.short_description, long_description = excluded.long_description, image_url = excluded.image_url,
  image_alt = excluded.image_alt, starting_price_cents = excluded.starting_price_cents, currency = excluded.currency,
  status = excluded.status, is_visible = excluded.is_visible, launch_phase = excluded.launch_phase,
  campaign_theme = excluded.campaign_theme, requires_provider_review = excluded.requires_provider_review,
  requires_prescription = excluded.requires_prescription, requires_compliance_review = excluded.requires_compliance_review,
  requires_pharmacy_verification = excluded.requires_pharmacy_verification;

insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'progesterone-capsules-v1', '100mg, 30 capsules', 'Capsule', '100mg', '30 capsules', 4900, 'usd', 'one_time', null, true, 0
from public.catalog_products p where p.slug = 'progesterone-capsules'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;
insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'progesterone-capsules-v2', '200mg, 30 capsules', 'Capsule', '200mg', '30 capsules', 6900, 'usd', 'one_time', null, true, 1
from public.catalog_products p where p.slug = 'progesterone-capsules'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;

insert into public.catalog_products
  (slug, app_product_id, display_name, short_name, subtitle, category, dosage_form_summary,
   short_description, long_description, image_url, image_alt, starting_price_cents, currency,
   status, is_visible, launch_phase, campaign_theme, requires_provider_review, requires_prescription,
   requires_compliance_review, requires_pharmacy_verification)
values ('testosterone-cream', 'p27', 'Testosterone Cream', 'Testosterone Cream', 'Provider-directed hormone therapy', 'womens-hormone-therapy', 'Cream',
   'A topical testosterone cream prescribed as part of provider-directed hormone therapy.', 'Prescription option available following licensed-provider evaluation. Exact formulation, concentration, and treatment plan are determined by the prescribing provider and dispensing pharmacy.', '/images/products/ChatGPT_Image_Jul_31,_2026,_04_22_43_PM.png', 'Testosterone cream, a provider-directed hormone therapy option', 7900, 'usd',
   'active', true, null, null, true, true,
   true, true)
on conflict (slug) do update set
  app_product_id = excluded.app_product_id, display_name = excluded.display_name, short_name = excluded.short_name,
  subtitle = excluded.subtitle, category = excluded.category, dosage_form_summary = excluded.dosage_form_summary,
  short_description = excluded.short_description, long_description = excluded.long_description, image_url = excluded.image_url,
  image_alt = excluded.image_alt, starting_price_cents = excluded.starting_price_cents, currency = excluded.currency,
  status = excluded.status, is_visible = excluded.is_visible, launch_phase = excluded.launch_phase,
  campaign_theme = excluded.campaign_theme, requires_provider_review = excluded.requires_provider_review,
  requires_prescription = excluded.requires_prescription, requires_compliance_review = excluded.requires_compliance_review,
  requires_pharmacy_verification = excluded.requires_pharmacy_verification;

insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'testosterone-cream-v1', '5mg/g, 30g', 'Cream', '5mg/g', '30g', 7900, 'usd', 'one_time', null, true, 0
from public.catalog_products p where p.slug = 'testosterone-cream'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;

insert into public.catalog_products
  (slug, app_product_id, display_name, short_name, subtitle, category, dosage_form_summary,
   short_description, long_description, image_url, image_alt, starting_price_cents, currency,
   status, is_visible, launch_phase, campaign_theme, requires_provider_review, requires_prescription,
   requires_compliance_review, requires_pharmacy_verification)
values ('nad-plus', 'p9', 'NAD+', 'NAD+', 'Provider-directed compounded formulation', 'longevity-cognitive', 'Nasal Spray, Injection',
   'A provider-directed compounded NAD+ formulation, available in nasal spray and injection.', 'Provider-directed compounded formulation available only following eligibility review. Exact formulation and availability are determined by the prescribing provider and dispensing pharmacy.', '/images/products/file_0000000081dc822f831112a2c1e5d3d9 copy.png', 'NAD+ compounded formulation, provider-directed, available as nasal spray or injection', 14900, 'usd',
   'active', true, null, null, true, true,
   true, true)
on conflict (slug) do update set
  app_product_id = excluded.app_product_id, display_name = excluded.display_name, short_name = excluded.short_name,
  subtitle = excluded.subtitle, category = excluded.category, dosage_form_summary = excluded.dosage_form_summary,
  short_description = excluded.short_description, long_description = excluded.long_description, image_url = excluded.image_url,
  image_alt = excluded.image_alt, starting_price_cents = excluded.starting_price_cents, currency = excluded.currency,
  status = excluded.status, is_visible = excluded.is_visible, launch_phase = excluded.launch_phase,
  campaign_theme = excluded.campaign_theme, requires_provider_review = excluded.requires_provider_review,
  requires_prescription = excluded.requires_prescription, requires_compliance_review = excluded.requires_compliance_review,
  requires_pharmacy_verification = excluded.requires_pharmacy_verification;

insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'nad-plus-v1', 'Nasal Spray, 50mcg/50mcg per spray, 10mL', 'Nasal Spray', '50mcg/50mcg per spray', '10mL', 14900, 'usd', 'one_time', null, true, 0
from public.catalog_products p where p.slug = 'nad-plus'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;
insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'nad-plus-v2', 'Injection, 100mg/mL, 5mL', 'Injection', '100mg/mL', '5mL', 19900, 'usd', 'one_time', null, true, 1
from public.catalog_products p where p.slug = 'nad-plus'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;
insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'nad-plus-v3', 'Injection, 100mg/mL, 10mL', 'Injection', '100mg/mL', '10mL', 21900, 'usd', 'one_time', null, true, 2
from public.catalog_products p where p.slug = 'nad-plus'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;

insert into public.catalog_products
  (slug, app_product_id, display_name, short_name, subtitle, category, dosage_form_summary,
   short_description, long_description, image_url, image_alt, starting_price_cents, currency,
   status, is_visible, launch_phase, campaign_theme, requires_provider_review, requires_prescription,
   requires_compliance_review, requires_pharmacy_verification)
values ('selank', 'p48', 'Selank Injection', 'Selank', 'Provider-directed compounded formulation', 'longevity-cognitive', 'Injection',
   'A provider-directed compounded Selank injection, available only after eligibility review.', 'Provider-directed compounded formulation available only following eligibility review. Exact formulation and availability are determined by the prescribing provider and dispensing pharmacy.', '/images/products/file_0000000081dc822f831112a2c1e5d3d9 copy.png', 'Selank injection, a provider-directed compounded formulation', 12900, 'usd',
   'active', true, null, null, true, true,
   true, true)
on conflict (slug) do update set
  app_product_id = excluded.app_product_id, display_name = excluded.display_name, short_name = excluded.short_name,
  subtitle = excluded.subtitle, category = excluded.category, dosage_form_summary = excluded.dosage_form_summary,
  short_description = excluded.short_description, long_description = excluded.long_description, image_url = excluded.image_url,
  image_alt = excluded.image_alt, starting_price_cents = excluded.starting_price_cents, currency = excluded.currency,
  status = excluded.status, is_visible = excluded.is_visible, launch_phase = excluded.launch_phase,
  campaign_theme = excluded.campaign_theme, requires_provider_review = excluded.requires_provider_review,
  requires_prescription = excluded.requires_prescription, requires_compliance_review = excluded.requires_compliance_review,
  requires_pharmacy_verification = excluded.requires_pharmacy_verification;

insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'selank-v1', '5mg/mL, 2mL', 'Injection', '5mg/mL', '2mL', 12900, 'usd', 'one_time', null, true, 0
from public.catalog_products p where p.slug = 'selank'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;

insert into public.catalog_products
  (slug, app_product_id, display_name, short_name, subtitle, category, dosage_form_summary,
   short_description, long_description, image_url, image_alt, starting_price_cents, currency,
   status, is_visible, launch_phase, campaign_theme, requires_provider_review, requires_prescription,
   requires_compliance_review, requires_pharmacy_verification)
values ('semax', 'p47', 'Semax Injection', 'Semax', 'Provider-directed compounded formulation', 'longevity-cognitive', 'Injection',
   'A provider-directed compounded Semax injection, available only after eligibility review.', 'Provider-directed compounded formulation available only following eligibility review. Exact formulation and availability are determined by the prescribing provider and dispensing pharmacy.', '/images/products/file_0000000081dc822f831112a2c1e5d3d9 copy.png', 'Semax injection, a provider-directed compounded formulation', 12900, 'usd',
   'active', true, null, null, true, true,
   true, true)
on conflict (slug) do update set
  app_product_id = excluded.app_product_id, display_name = excluded.display_name, short_name = excluded.short_name,
  subtitle = excluded.subtitle, category = excluded.category, dosage_form_summary = excluded.dosage_form_summary,
  short_description = excluded.short_description, long_description = excluded.long_description, image_url = excluded.image_url,
  image_alt = excluded.image_alt, starting_price_cents = excluded.starting_price_cents, currency = excluded.currency,
  status = excluded.status, is_visible = excluded.is_visible, launch_phase = excluded.launch_phase,
  campaign_theme = excluded.campaign_theme, requires_provider_review = excluded.requires_provider_review,
  requires_prescription = excluded.requires_prescription, requires_compliance_review = excluded.requires_compliance_review,
  requires_pharmacy_verification = excluded.requires_pharmacy_verification;

insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'semax-v1', '5mg/mL, 2mL', 'Injection', '5mg/mL', '2mL', 12900, 'usd', 'one_time', null, true, 0
from public.catalog_products p where p.slug = 'semax'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;

insert into public.catalog_products
  (slug, app_product_id, display_name, short_name, subtitle, category, dosage_form_summary,
   short_description, long_description, image_url, image_alt, starting_price_cents, currency,
   status, is_visible, launch_phase, campaign_theme, requires_provider_review, requires_prescription,
   requires_compliance_review, requires_pharmacy_verification)
values ('selank-semax-nasal-spray', 'p68', 'Selank + Semax Blend Nasal Spray', 'Selank + Semax Blend', 'Provider-directed compounded formulation', 'longevity-cognitive', 'Nasal Spray',
   'A provider-directed compounded Selank and Semax blend nasal spray, available only after eligibility review.', 'Provider-directed compounded formulation available only following eligibility review. Exact formulation and availability are determined by the prescribing provider and dispensing pharmacy.', '/images/products/nasal-spray.png', 'Selank and Semax blend nasal spray, a provider-directed compounded formulation', 14900, 'usd',
   'active', true, null, null, true, true,
   true, true)
on conflict (slug) do update set
  app_product_id = excluded.app_product_id, display_name = excluded.display_name, short_name = excluded.short_name,
  subtitle = excluded.subtitle, category = excluded.category, dosage_form_summary = excluded.dosage_form_summary,
  short_description = excluded.short_description, long_description = excluded.long_description, image_url = excluded.image_url,
  image_alt = excluded.image_alt, starting_price_cents = excluded.starting_price_cents, currency = excluded.currency,
  status = excluded.status, is_visible = excluded.is_visible, launch_phase = excluded.launch_phase,
  campaign_theme = excluded.campaign_theme, requires_provider_review = excluded.requires_provider_review,
  requires_prescription = excluded.requires_prescription, requires_compliance_review = excluded.requires_compliance_review,
  requires_pharmacy_verification = excluded.requires_pharmacy_verification;

insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'selank-semax-nasal-spray-v1', '50mcg/50mcg per spray, 10mL', 'Nasal Spray', '50mcg/50mcg per spray', '10mL', 14900, 'usd', 'one_time', null, true, 0
from public.catalog_products p where p.slug = 'selank-semax-nasal-spray'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;

insert into public.catalog_products
  (slug, app_product_id, display_name, short_name, subtitle, category, dosage_form_summary,
   short_description, long_description, image_url, image_alt, starting_price_cents, currency,
   status, is_visible, launch_phase, campaign_theme, requires_provider_review, requires_prescription,
   requires_compliance_review, requires_pharmacy_verification)
values ('bpc-157-tb-500', 'p41', 'BPC-157/TB-500 Blend', 'BPC-157/TB-500', 'Wolverine Blend', 'recovery-performance', 'Capsule, Injection',
   'A provider-directed compounded BPC-157/TB-500 blend, available in capsules and injection.', 'Provider-directed compounded formulation available only following eligibility review. Exact formulation and availability are determined by the prescribing provider and dispensing pharmacy.', '/images/products/file_0000000081dc822f831112a2c1e5d3d9 copy.png', 'BPC-157/TB-500 blend, a provider-directed compounded formulation in capsule and injection forms', 9900, 'usd',
   'active', true, null, null, true, true,
   true, true)
on conflict (slug) do update set
  app_product_id = excluded.app_product_id, display_name = excluded.display_name, short_name = excluded.short_name,
  subtitle = excluded.subtitle, category = excluded.category, dosage_form_summary = excluded.dosage_form_summary,
  short_description = excluded.short_description, long_description = excluded.long_description, image_url = excluded.image_url,
  image_alt = excluded.image_alt, starting_price_cents = excluded.starting_price_cents, currency = excluded.currency,
  status = excluded.status, is_visible = excluded.is_visible, launch_phase = excluded.launch_phase,
  campaign_theme = excluded.campaign_theme, requires_provider_review = excluded.requires_provider_review,
  requires_prescription = excluded.requires_prescription, requires_compliance_review = excluded.requires_compliance_review,
  requires_pharmacy_verification = excluded.requires_pharmacy_verification;

insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'bpc-157-tb-500-v1', 'Capsule, 500mcg/500mcg per capsule, 30 capsules', 'Capsule', '500mcg/500mcg per capsule', '30 capsules', 9900, 'usd', 'one_time', null, true, 0
from public.catalog_products p where p.slug = 'bpc-157-tb-500'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;
insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'bpc-157-tb-500-v2', 'Injection, 1.66mg/3.33mg per mL, 3mL', 'Injection', '1.66mg/3.33mg per mL', '3mL', 19900, 'usd', 'one_time', null, true, 1
from public.catalog_products p where p.slug = 'bpc-157-tb-500'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;

insert into public.catalog_products
  (slug, app_product_id, display_name, short_name, subtitle, category, dosage_form_summary,
   short_description, long_description, image_url, image_alt, starting_price_cents, currency,
   status, is_visible, launch_phase, campaign_theme, requires_provider_review, requires_prescription,
   requires_compliance_review, requires_pharmacy_verification)
values ('tretinoin-cream', 'p69', 'Tretinoin Cream', 'Tretinoin', 'Prescription skin care', 'prescription-skin-hair', 'Cream',
   'A prescription topical tretinoin cream available following licensed-provider review.', 'Prescription option available following licensed-provider evaluation. Exact formulation, concentration, and treatment plan are determined by the prescribing provider and dispensing pharmacy.', '/images/products/ChatGPT_Image_Jul_31,_2026,_04_22_43_PM.png', 'Tretinoin cream, a prescription topical skin-care treatment', 7900, 'usd',
   'active', true, null, null, true, true,
   true, true)
on conflict (slug) do update set
  app_product_id = excluded.app_product_id, display_name = excluded.display_name, short_name = excluded.short_name,
  subtitle = excluded.subtitle, category = excluded.category, dosage_form_summary = excluded.dosage_form_summary,
  short_description = excluded.short_description, long_description = excluded.long_description, image_url = excluded.image_url,
  image_alt = excluded.image_alt, starting_price_cents = excluded.starting_price_cents, currency = excluded.currency,
  status = excluded.status, is_visible = excluded.is_visible, launch_phase = excluded.launch_phase,
  campaign_theme = excluded.campaign_theme, requires_provider_review = excluded.requires_provider_review,
  requires_prescription = excluded.requires_prescription, requires_compliance_review = excluded.requires_compliance_review,
  requires_pharmacy_verification = excluded.requires_pharmacy_verification;

insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'tretinoin-cream-v1', '0.025%, 20g', 'Cream', '0.025%', '20g', 7900, 'usd', 'one_time', null, true, 0
from public.catalog_products p where p.slug = 'tretinoin-cream'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;
insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'tretinoin-cream-v2', '0.05%, 20g', 'Cream', '0.05%', '20g', 8900, 'usd', 'one_time', null, true, 1
from public.catalog_products p where p.slug = 'tretinoin-cream'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;
insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'tretinoin-cream-v3', '0.1%, 20g', 'Cream', '0.1%', '20g', 10900, 'usd', 'one_time', null, true, 2
from public.catalog_products p where p.slug = 'tretinoin-cream'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;

insert into public.catalog_products
  (slug, app_product_id, display_name, short_name, subtitle, category, dosage_form_summary,
   short_description, long_description, image_url, image_alt, starting_price_cents, currency,
   status, is_visible, launch_phase, campaign_theme, requires_provider_review, requires_prescription,
   requires_compliance_review, requires_pharmacy_verification)
values ('minoxidil-topical', 'p70', 'Minoxidil Combination Topical Formula', 'Minoxidil Topical', 'Prescription hair care', 'prescription-skin-hair', 'Topical Solution',
   'A compounded topical formula featuring minoxidil, personalized by the prescribing provider and dispensing pharmacy.', 'Prescription hair-care option available following licensed-provider review. Exact compounded formulation is determined by the prescribing provider and dispensing pharmacy.', '/images/products/ChatGPT_Image_Aug_3,_2026,_04_14_54_PM.png', 'Minoxidil combination topical formula, a prescription hair-care treatment', 11900, 'usd',
   'active', true, null, null, true, true,
   true, true)
on conflict (slug) do update set
  app_product_id = excluded.app_product_id, display_name = excluded.display_name, short_name = excluded.short_name,
  subtitle = excluded.subtitle, category = excluded.category, dosage_form_summary = excluded.dosage_form_summary,
  short_description = excluded.short_description, long_description = excluded.long_description, image_url = excluded.image_url,
  image_alt = excluded.image_alt, starting_price_cents = excluded.starting_price_cents, currency = excluded.currency,
  status = excluded.status, is_visible = excluded.is_visible, launch_phase = excluded.launch_phase,
  campaign_theme = excluded.campaign_theme, requires_provider_review = excluded.requires_provider_review,
  requires_prescription = excluded.requires_prescription, requires_compliance_review = excluded.requires_compliance_review,
  requires_pharmacy_verification = excluded.requires_pharmacy_verification;

insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'minoxidil-topical-v1', '1% plus pharmacy-selected actives, 60mL', 'Topical Solution', '1% plus pharmacy-selected actives', '60mL', 11900, 'usd', 'one_time', null, true, 0
from public.catalog_products p where p.slug = 'minoxidil-topical'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;

insert into public.catalog_products
  (slug, app_product_id, display_name, short_name, subtitle, category, dosage_form_summary,
   short_description, long_description, image_url, image_alt, starting_price_cents, currency,
   status, is_visible, launch_phase, campaign_theme, requires_provider_review, requires_prescription,
   requires_compliance_review, requires_pharmacy_verification)
values ('bimatoprost-solution', 'p71', 'Bimatoprost Solution', 'Bimatoprost', 'Prescription eyelash care', 'prescription-skin-hair', 'Solution',
   'A prescription bimatoprost solution available following licensed-provider review.', 'Prescription option available following licensed-provider evaluation. Exact formulation, concentration, and treatment plan are determined by the prescribing provider and dispensing pharmacy.', '/images/products/ChatGPT_Image_Aug_3,_2026,_04_16_27_PM.png', 'Bimatoprost solution, a prescription treatment', 8900, 'usd',
   'active', true, null, null, true, true,
   true, true)
on conflict (slug) do update set
  app_product_id = excluded.app_product_id, display_name = excluded.display_name, short_name = excluded.short_name,
  subtitle = excluded.subtitle, category = excluded.category, dosage_form_summary = excluded.dosage_form_summary,
  short_description = excluded.short_description, long_description = excluded.long_description, image_url = excluded.image_url,
  image_alt = excluded.image_alt, starting_price_cents = excluded.starting_price_cents, currency = excluded.currency,
  status = excluded.status, is_visible = excluded.is_visible, launch_phase = excluded.launch_phase,
  campaign_theme = excluded.campaign_theme, requires_provider_review = excluded.requires_provider_review,
  requires_prescription = excluded.requires_prescription, requires_compliance_review = excluded.requires_compliance_review,
  requires_pharmacy_verification = excluded.requires_pharmacy_verification;

insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'bimatoprost-solution-v1', '0.03%, 2.5mL', 'Solution', '0.03%', '2.5mL', 8900, 'usd', 'one_time', null, true, 0
from public.catalog_products p where p.slug = 'bimatoprost-solution'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;

insert into public.catalog_products
  (slug, app_product_id, display_name, short_name, subtitle, category, dosage_form_summary,
   short_description, long_description, image_url, image_alt, starting_price_cents, currency,
   status, is_visible, launch_phase, campaign_theme, requires_provider_review, requires_prescription,
   requires_compliance_review, requires_pharmacy_verification)
values ('sermorelin', 'p12', 'Sermorelin', 'Sermorelin', 'Provider-directed compounded formulation', 'longevity-cognitive', 'Injection',
   'A provider-directed compounded Sermorelin formulation.', 'Provider-directed compounded formulation available only following eligibility review. Exact formulation and availability are determined by the prescribing provider and dispensing pharmacy.', '/images/products/file_0000000081dc822f831112a2c1e5d3d9 copy.png', 'Sermorelin, a provider-directed compounded formulation', 11900, 'usd',
   'future', false, 2, 'future longevity release', true, true,
   true, true)
on conflict (slug) do update set
  app_product_id = excluded.app_product_id, display_name = excluded.display_name, short_name = excluded.short_name,
  subtitle = excluded.subtitle, category = excluded.category, dosage_form_summary = excluded.dosage_form_summary,
  short_description = excluded.short_description, long_description = excluded.long_description, image_url = excluded.image_url,
  image_alt = excluded.image_alt, starting_price_cents = excluded.starting_price_cents, currency = excluded.currency,
  status = excluded.status, is_visible = excluded.is_visible, launch_phase = excluded.launch_phase,
  campaign_theme = excluded.campaign_theme, requires_provider_review = excluded.requires_provider_review,
  requires_prescription = excluded.requires_prescription, requires_compliance_review = excluded.requires_compliance_review,
  requires_pharmacy_verification = excluded.requires_pharmacy_verification;

insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'sermorelin-v1', '9mg/mL, 3mL', 'Injection', '9mg/mL', '3mL', 11900, 'usd', 'one_time', null, true, 0
from public.catalog_products p where p.slug = 'sermorelin'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;

insert into public.catalog_products
  (slug, app_product_id, display_name, short_name, subtitle, category, dosage_form_summary,
   short_description, long_description, image_url, image_alt, starting_price_cents, currency,
   status, is_visible, launch_phase, campaign_theme, requires_provider_review, requires_prescription,
   requires_compliance_review, requires_pharmacy_verification)
values ('minoxidil-tablets', 'p72', 'Minoxidil Tablets', 'Minoxidil Tablets', 'Prescription hair care', 'prescription-skin-hair', 'Capsule',
   'Provider-directed oral minoxidil tablets.', 'Prescription option available following licensed-provider evaluation. Exact formulation, concentration, and treatment plan are determined by the prescribing provider and dispensing pharmacy.', '/images/products/file_00000000e110822fb1dd36d19b3c9896 copy.png', 'Minoxidil tablets, a prescription hair-care treatment', 7900, 'usd',
   'future', false, 2, 'future hair restoration release', true, true,
   true, true)
on conflict (slug) do update set
  app_product_id = excluded.app_product_id, display_name = excluded.display_name, short_name = excluded.short_name,
  subtitle = excluded.subtitle, category = excluded.category, dosage_form_summary = excluded.dosage_form_summary,
  short_description = excluded.short_description, long_description = excluded.long_description, image_url = excluded.image_url,
  image_alt = excluded.image_alt, starting_price_cents = excluded.starting_price_cents, currency = excluded.currency,
  status = excluded.status, is_visible = excluded.is_visible, launch_phase = excluded.launch_phase,
  campaign_theme = excluded.campaign_theme, requires_provider_review = excluded.requires_provider_review,
  requires_prescription = excluded.requires_prescription, requires_compliance_review = excluded.requires_compliance_review,
  requires_pharmacy_verification = excluded.requires_pharmacy_verification;

insert into public.catalog_variants
  (product_id, variant_key, display_name, dosage_form, strength, size, price_cents, currency, billing_type, billing_interval, is_active, sort_order)
select p.id, 'minoxidil-tablets-v1', '2.5mg, 30 tablets', 'Capsule', '2.5mg', '30 tablets', 7900, 'usd', 'one_time', null, true, 0
from public.catalog_products p where p.slug = 'minoxidil-tablets'
on conflict (product_id, variant_key) do update set
  display_name = excluded.display_name, dosage_form = excluded.dosage_form, strength = excluded.strength, size = excluded.size,
  price_cents = excluded.price_cents, currency = excluded.currency, billing_type = excluded.billing_type,
  billing_interval = excluded.billing_interval, is_active = excluded.is_active, sort_order = excluded.sort_order;

insert into public.catalog_memberships
  (slug, app_product_id, display_name, brand_name, short_description, long_description, monthly_price_cents, currency,
   billing_interval, initial_term_months, locked_rate, included_formulations, maximum_included_formulation,
   provider_review_required, prescription_guaranteed, shipping_included, status, is_visible)
values ('semaglutide-membership', 'm1', 'Semaglutide Membership', 'Bare Balance', 'One membership. One predictable monthly price. Provider-directed Semaglutide + B6 treatment.', 'A provider-guided Semaglutide membership. Your monthly membership price stays the same as your provider adjusts your eligible treatment within the included program while you remain continuously enrolled.', 19900, 'usd',
   'month', 3, true, '["1mg/1mg per mL, 2mL","2mg/2mg per mL, 2mL","5mg/2mg per mL, 2mL"]'::jsonb, '5mg/2mg per mL, 2mL',
   true, false, false, 'active', true)
on conflict (slug) do update set
  app_product_id = excluded.app_product_id, display_name = excluded.display_name, brand_name = excluded.brand_name,
  short_description = excluded.short_description, long_description = excluded.long_description,
  monthly_price_cents = excluded.monthly_price_cents, currency = excluded.currency, billing_interval = excluded.billing_interval,
  initial_term_months = excluded.initial_term_months, locked_rate = excluded.locked_rate,
  included_formulations = excluded.included_formulations, maximum_included_formulation = excluded.maximum_included_formulation,
  provider_review_required = excluded.provider_review_required, prescription_guaranteed = excluded.prescription_guaranteed,
  shipping_included = excluded.shipping_included, status = excluded.status, is_visible = excluded.is_visible;

insert into public.catalog_memberships
  (slug, app_product_id, display_name, brand_name, short_description, long_description, monthly_price_cents, currency,
   billing_interval, initial_term_months, locked_rate, included_formulations, maximum_included_formulation,
   provider_review_required, prescription_guaranteed, shipping_included, status, is_visible)
values ('tirzepatide-membership', 'm2', 'Tirzepatide Membership', 'Bare Momentum', 'One predictable monthly rate through the included program maximum. Provider-directed Tirzepatide + B6 treatment.', 'A provider-guided Tirzepatide membership. Your monthly membership price stays the same as your provider adjusts your eligible treatment within the included program through 25mg/2mg per mL, 2mL while you remain continuously enrolled.', 24900, 'usd',
   'month', 3, true, '["5mg/2mg per mL, 2mL","15mg/2mg per mL, 2mL","25mg/2mg per mL, 2mL"]'::jsonb, '25mg/2mg per mL, 2mL',
   true, false, false, 'active', true)
on conflict (slug) do update set
  app_product_id = excluded.app_product_id, display_name = excluded.display_name, brand_name = excluded.brand_name,
  short_description = excluded.short_description, long_description = excluded.long_description,
  monthly_price_cents = excluded.monthly_price_cents, currency = excluded.currency, billing_interval = excluded.billing_interval,
  initial_term_months = excluded.initial_term_months, locked_rate = excluded.locked_rate,
  included_formulations = excluded.included_formulations, maximum_included_formulation = excluded.maximum_included_formulation,
  provider_review_required = excluded.provider_review_required, prescription_guaranteed = excluded.prescription_guaranteed,
  shipping_included = excluded.shipping_included, status = excluded.status, is_visible = excluded.is_visible;

insert into public.catalog_memberships
  (slug, app_product_id, display_name, brand_name, short_description, long_description, monthly_price_cents, currency,
   billing_interval, initial_term_months, locked_rate, included_formulations, maximum_included_formulation,
   provider_review_required, prescription_guaranteed, shipping_included, status, is_visible)
values ('elite-wellness-membership', '', 'Bare Elite Wellness', 'Bare Elite Wellness', 'Member pricing on other wellness products.', 'Member pricing on other wellness products, priority processing, and early access to new therapies.', 4900, 'usd',
   'month', 3, true, '[]'::jsonb, '',
   true, false, false, 'inactive', false)
on conflict (slug) do update set
  app_product_id = excluded.app_product_id, display_name = excluded.display_name, brand_name = excluded.brand_name,
  short_description = excluded.short_description, long_description = excluded.long_description,
  monthly_price_cents = excluded.monthly_price_cents, currency = excluded.currency, billing_interval = excluded.billing_interval,
  initial_term_months = excluded.initial_term_months, locked_rate = excluded.locked_rate,
  included_formulations = excluded.included_formulations, maximum_included_formulation = excluded.maximum_included_formulation,
  provider_review_required = excluded.provider_review_required, prescription_guaranteed = excluded.prescription_guaranteed,
  shipping_included = excluded.shipping_included, status = excluded.status, is_visible = excluded.is_visible;

